services:
  frontend:
    build:
      context: ./digital-stock-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080

  backend:
    build:
      context: ./digital-stock-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/digital-stock-db
      SPRING_DATASOURCE_USERNAME: janaina
      SPRING_DATASOURCE_PASSWORD: enzo

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: digital-stock-db
      POSTGRES_USER: janaina
      POSTGRES_PASSWORD: enzo
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
